
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Build Packages"
          command: npm run lint
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Test Packages"
          command: npm run test
  analyse:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Audit Packages"
          command: npm audit

workflows:
  my-workspace:
    jobs:
      - build
      - test
      - analyse:
          requires
            - test
